server:
  port: 8085
  tomcat:
    reject-illegal-header: false
    connection-timeout: 60000

sa-token:
  token-name: satoken      # token名称（默认：satoken）
  timeout: 36000000        # token有效期，单位：秒（默认30分钟）
  is-concurrent: true     # 是否允许同一账号多地登录（默认：true）
  is-share: true           # 是否在同一个会话中共享 Token（默认：true）
  token-style: uuid        # token 生成的样式（默认：uuid）
  is-log: false            # 是否输出操作日志

spring:
  flyway:
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  mvc:
    view:
      prefix: /
      suffix: html
    async:
      request-timeout: -1
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:sqlite:db/tgDrive.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.skydevs.tgdrive
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: sqlite
  support-methods-arguments: true
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致
